### PR TITLE
James bacon poll

### PR DESCRIPTION
**Pull request by JamesBacon**
I saw you were using poll.js and was like, why. So here's one that works all within Discord.js.
It was coding for the master branch of Discord.js so you should have to change too many lines to make it work on stable.

### CODE REVIEW

**Comment by JamesBacon** [comment]
There are a few issues. At the moment the messageContent keeps the number for the time.

**Comment by JamesBacon** [comment]
Also it was coded with msg, not message. You can fix that.

**Comment by alli2191** [comment]
It's in poll.js so that it's not cluttering up the main script and I can edit/delete it without risking accidentally breaking the main script (too much). will probably do the same for the purge function eventually, but it adds the headache of figuring out which variables it needs passed to it to work. I'll check out the code you've posted, looks like it worked in the discord 💯 😄

**Comment by alli2191** [comment]
Unceremoniously copy-pasted into 'working' because I couldn't figure out how to push this to the working branch lol. Seems to be functioning now. Will tidy & merge working into master. @JamesBacon

**Pull request closed without merging**
